services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    container_name: jenkins
    privileged: true 
    user: root
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/jenkins:/var/jenkins_home
        #- /var/run/docker.sock:/var/run/docker.sock # Mount host Docker socket (if snap, then '/var/run/docker.sock')
        #- /usr/bin/docker:/usr/bin/docker:ro # Mount Docker binary (if snap use '/usr/bin/docker')
    networks:
      - jenkins-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config:/nginx-config
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./scripts:/scripts:ro
        #entrypoint: ["/bin/sh", "-c", "/wait-for-certs.sh && nginx -g 'daemon off;'"]
    entrypoint: ["/scripts/nginx-entry.sh"]
    depends_on:
      - jenkins
    networks:
      - jenkins-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./scripts:/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/scripts/certbot-entry.sh"]
    depends_on:
      - nginx
    networks:
      - jenkins-network

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge
